(function(g){var window=this;var cGa=function(a,b){a.va("onAutonavCoundownStarted",b)},e3=function(a,b,c){var d=b.Ma();
g.K(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.ue(c?c:"mqdefault.jpg");var f=null,h=null;b instanceof g.rI&&(b.lengthText?(f=b.lengthText||null,h=b.tu||null):b.lengthSeconds&&(f=g.DM(b.lengthSeconds),h=g.DM(b.lengthSeconds,!0)));var l=!!e;e=l&&"RD"===(new g.$N(e.substr(0,2),e.substr(2))).type;var m=b instanceof g.rI?b.isLivePlayback:null,n=b instanceof g.rI?b.isUpcoming:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:
b.author,aria_label:b.qq||g.sK("$TITLE afspelen",{TITLE:b.title}),duration:f,timestamp:h,url:b.El(),is_live:m,is_upcoming:n,is_list:l,is_mix:e,background:c?"background-image: url("+c+")":"",views_and_publish_time:d.shortViewCount?d.shortViewCount+" \u2022 "+d.publishedTimeText:d.publishedTimeText,autoplayAlternativeHeader:b.uq};b instanceof g.aO&&(d.playlist_length=b.length);a.update(d)},f3=function(a){var b=a.S(),c=b.B;
g.U.call(this,{G:"a",L:"ytp-autonav-suggestion-card",T:{href:"{{url}}",target:c?b.F:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},R:[{G:"div",ia:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],T:{style:"{{background}}"},R:[{G:"div",T:{"aria-label":"{{timestamp}}"},ia:["ytp-autonav-timestamp"],ba:"{{duration}}"},{G:"div",ia:["ytp-autonav-live-stamp"],ba:"Live"},{G:"div",
ia:["ytp-autonav-upcoming-stamp"],ba:"Binnenkort"},{G:"div",L:"ytp-autonav-list-overlay",R:[{G:"div",L:"ytp-autonav-mix-text",ba:"Mix"},{G:"div",L:"ytp-autonav-mix-icon"}]}]},{G:"div",ia:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],ba:"{{title}}"},{G:"div",ia:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],ba:"{{author}}"},{G:"div",ia:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],ba:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.u=c;this.ya("click",this.onClick);this.ya("keypress",this.B)},h3=function(a,b){b=void 0===b?!1:b;
g.U.call(this,{G:"div",L:"ytp-autonav-endscreen-countdown-container"});var c=this;this.F=b;this.C=0;var d=a.S(),e=d.B;this.J=a;this.suggestion=null;this.u=new g.U({G:"div",L:"ytp-autonav-endscreen-upnext-container",T:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},R:[{G:"div",L:"ytp-autonav-endscreen-upnext-header"},{G:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",ba:"{{autoplayAlternativeHeader}}"},
{G:"a",L:"ytp-autonav-endscreen-link-container",T:{href:"{{url}}",target:e?d.F:""},R:[{G:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",T:{style:"{{background}}"},R:[{G:"div",T:{"aria-label":"{{timestamp}}"},ia:["ytp-autonav-timestamp"],ba:"{{duration}}"},{G:"div",ia:["ytp-autonav-live-stamp"],ba:"Live"},{G:"div",ia:["ytp-autonav-upcoming-stamp"],ba:"Binnenkort"}]},{G:"div",L:"ytp-autonav-endscreen-video-info",R:[{G:"div",L:"ytp-autonav-endscreen-premium-badge"},{G:"div",L:"ytp-autonav-endscreen-upnext-title",
ba:"{{title}}"},{G:"div",L:"ytp-autonav-endscreen-upnext-author",ba:"{{author}}"},{G:"div",L:"ytp-autonav-view-and-date",ba:"{{views_and_publish_time}}"},{G:"div",L:"ytp-autonav-author-and-view",ba:"{{author_and_views}}"}]}]}]});g.C(this,this.u);this.u.fa(this.element);e||this.P(this.u.ha("ytp-autonav-endscreen-link-container"),"click",this.KE);this.J.Lb(this.element,this,115127);this.J.Lb(this.u.ha("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.U({G:"div",L:"ytp-autonav-overlay"});
g.C(this,this.overlay);this.overlay.fa(this.element);this.B=new g.U({G:"div",L:"ytp-autonav-endscreen-button-container"});g.C(this,this.B);this.B.fa(this.element);this.cancelButton=new g.U({G:"button",ia:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],T:{"aria-label":"Autoplay annuleren"},ba:"Annuleren"});g.C(this,this.cancelButton);this.cancelButton.fa(this.B.element);this.cancelButton.ya("click",this.CL,this);this.J.Lb(this.cancelButton.element,this,115129);
this.playButton=new g.U({G:"a",ia:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],T:{href:"{{url}}",role:"button","aria-label":"Volgende video afspelen"},ba:"Nu spelen"});g.C(this,this.playButton);this.playButton.fa(this.B.element);this.playButton.ya("click",this.KE,this);this.J.Lb(this.playButton.element,this,115130);this.D=new g.E(function(){g3(c)},500);
g.C(this,this.D);this.JE();this.P(a,"autonavvisibility",this.JE)},g3=function(a){var b=i3(a),c=Math.min(a.C?Date.now()-a.C:0,b);
j3(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Ug()?a.select(!0):a.Ug()&&a.D.start()},i3=function(a){var b=a.J.gn();
return 0<=b?b:g.O(a.J.S().experiments,"autoplay_time")||1E4},j3=function(a,b){b=void 0===b?-1:b;
var c=a.u.ha("ytp-autonav-endscreen-upnext-header");g.Ie(c);if(0<=b){var d=String(b),e="Volgende video over $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],f="Volgende video over $SECONDS".indexOf(e);if(0<=f){c.appendChild(g.He("Volgende video over $SECONDS".slice(0,f)));var h=g.Ge("span");g.un(h,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Qe(h,d);c.appendChild(h);c.appendChild(g.He("Volgende video over $SECONDS".slice(f+e.length)));return}}g.Qe(c,"Volgende")},k3=function(a,b){g.U.call(this,
{G:"div",
ia:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},m3=function(a){g.U.call(this,{G:"div",
ia:["ytp-upnext","ytp-player-content"],T:{"aria-label":"{{aria_label}}"},R:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",T:{style:"{{background}}"}},{G:"span",L:"ytp-upnext-top",R:[{G:"span",L:"ytp-upnext-header",ba:"Hierna"},{G:"span",L:"ytp-upnext-title",ba:"{{title}}"},{G:"span",L:"ytp-upnext-author",ba:"{{author}}"}]},{G:"a",L:"ytp-upnext-autoplay-icon",T:{role:"button",href:"{{url}}","aria-label":"Volgende video afspelen"},R:[{G:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
R:[{G:"circle",L:"ytp-svg-autoplay-circle",T:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",T:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",T:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",R:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
ba:"Autoplay is onderbroken"}]}]});this.api=a;this.cancelButton=null;this.F=this.ha("ytp-svg-autoplay-ring");this.C=this.notification=this.u=this.suggestion=null;this.D=new g.E(this.ut,5E3,this);this.B=0;var b=this.ha("ytp-upnext-cancel");this.cancelButton=new g.U({G:"button",ia:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:"0","aria-label":"Autoplay annuleren"},ba:"Annuleren"});g.C(this,this.cancelButton);this.cancelButton.ya("click",this.wM,this);this.cancelButton.fa(b);this.cancelButton&&
this.api.Lb(this.cancelButton.element,this,115129);g.C(this,this.D);this.api.Lb(this.element,this,18788);b=this.ha("ytp-upnext-autoplay-icon");this.P(b,"click",this.xM);this.api.Lb(b,this,115130);this.UE();this.P(a,"autonavvisibility",this.UE);this.P(a,"mdxnowautoplaying",this.zO);this.P(a,"mdxautoplaycanceled",this.AO);this.P(a,"mdxautoplayupnext",this.PH);l3(this)&&(a=(a=g.SN(this.api.Sa()))?a.QJ():null)&&this.PH(a);g.K(this.element,"ytp-upnext-mobile",this.api.S().u)},l3=function(a){return 3===
a.api.getPresentingPlayerType()},dGa=function(a,b){return b?b:0<=a.api.gn()?a.api.gn():g.O(a.api.S().experiments,"autoplay_time")||1E4},n3=function(a,b){var c=dGa(a,b),d=Math,e=d.min;
var f=(0,g.M)()-a.B;d=e.call(d,f,c);c=0===c?1:Math.min(d/c,1);a.F.setAttribute("stroke-dashoffset",""+-211*(c+1));1<=c&&a.Ug()&&!l3(a)?a.select(!0):a.Ug()&&a.u.start()},o3=function(a){k3.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=this.suggestions=null;this.table=new g.U({G:"div",L:"ytp-suggestion-panel",R:[{G:"div",ia:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],ba:"Meer video's"}]});this.K=new g.U({G:"div",L:"ytp-suggestions-container"});this.videos=[];this.C=null;this.F=this.I=!1;this.B=new h3(this.player);g.C(this,this.B);this.B.fa(this.element);a.getVideoData().kc?this.u=this.B:(this.u=new m3(a),g.WN(this.player,this.u.element,4),g.C(this,this.u));this.overlay=
new g.U({G:"div",L:"ytp-autonav-overlay-cancelled-state"});g.C(this,this.overlay);this.overlay.fa(this.element);this.D=new g.YN(this);g.C(this,this.D);g.C(this,this.table);this.table.fa(this.element);this.table.show();g.C(this,this.K);this.K.fa(this.table.element);this.hide()},eGa=function(a,b){return g.Mc(b.suggestions,function(c){c=g.VQ(a.player.S(),c);
g.C(a,c);return c})},p3=function(a){var b=a.wd();
b!==a.F&&(a.F=b,a.player.V("autonavvisibility"),a.F?(a.B!==a.u&&a.B.hide(),a.table.hide()):(a.B!==a.u&&a.B.show(),a.table.show()))},q3=function(a){k3.call(this,a,"subscribecard-endscreen");
this.u=new g.U({G:"div",L:"ytp-subscribe-card",R:[{G:"img",L:"ytp-author-image",T:{src:"{{profilePicture}}"}},{G:"div",L:"ytp-subscribe-card-right",R:[{G:"div",L:"ytp-author-name",ba:"{{author}}"},{G:"div",L:"html5-subscribe-button-container"}]}]});g.C(this,this.u);this.u.fa(this.element);var b=a.getVideoData();this.subscribeButton=new g.iP("Abonneren",null,"Afmelden",null,!0,!1,b.Hg,b.subscribed,"trailer-endscreen",null,null,a);g.C(this,this.subscribeButton);this.subscribeButton.fa(this.u.ha("html5-subscribe-button-container"));
this.P(a,"videodatachange",this.na);this.na();this.hide()},r3=function(a){var b=a.S(),c=g.tB||g.wg?{style:"will-change: opacity"}:void 0,d=b.B,e=["ytp-videowall-still"];
b.u&&e.push("ytp-videowall-show-text");g.U.call(this,{G:"a",ia:e,T:{href:"{{url}}",target:d?b.F:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},R:[{G:"div",L:"ytp-videowall-still-image",T:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",R:[{G:"span",L:"ytp-videowall-still-info-bg",R:[{G:"span",L:"ytp-videowall-still-info-content",T:c,R:[{G:"span",L:"ytp-videowall-still-info-title",ba:"{{title}}"},{G:"span",L:"ytp-videowall-still-info-author",
ba:"{{author_and_views}}"},{G:"span",L:"ytp-videowall-still-info-live",ba:"Live"},{G:"span",L:"ytp-videowall-still-info-duration",ba:"{{duration}}"}]}]}]},{G:"span",ia:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],R:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",L:"ytp-videowall-still-listlabel-length",R:[" (",{G:"span",ba:"{{playlist_length}}"},")"]}]},{G:"span",ia:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],R:[{G:"span",
L:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",L:"ytp-videowall-still-listlabel-length",ba:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.u=new g.YN(this);g.C(this,this.u);this.ya("click",this.onClick);this.ya("keypress",this.C);this.u.P(a,"videodatachange",this.Pa);a.Og(this.element,this);this.Pa()},s3=function(a){k3.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=this.suggestions=null;this.F=this.N=!1;this.K=null;this.B=new g.YN(this);g.C(this,this.B);this.I=new g.E(function(){g.J(b.element,"ytp-show-tiles")},0);
g.C(this,this.I);var c=new g.U({G:"button",ia:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":"Vorige"},R:[g.SL()]});g.C(this,c);c.fa(this.element);c.ya("click",this.FL,this);this.table=new g.LL({G:"div",L:"ytp-endscreen-content"});g.C(this,this.table);this.table.fa(this.element);c=new g.U({G:"button",ia:["ytp-button","ytp-endscreen-next"],T:{"aria-label":"Volgende"},R:[g.TL()]});g.C(this,c);c.fa(this.element);c.ya("click",this.EL,this);a.getVideoData().kc?this.u=new h3(a,!0):this.u=new m3(a);
g.C(this,this.u);g.WN(this.player,this.u.element,4);this.hide()},t3=function(a){return g.XN(a.player)&&a.tq()&&!a.D},fGa=function(a,b){return g.Mc(b.suggestions,function(c){c=g.VQ(a.J.S(),c);
g.C(a,c);return c})},u3=function(a){var b=a.wd();
b!==a.N&&(a.N=b,a.player.V("autonavvisibility"))},v3=function(a){g.hO.call(this,a);
var b=this;this.endScreen=null;this.u=this.B=this.C=!1;this.listeners=new g.YN(this);g.C(this,this.listeners);this.env=a.S();gGa(a)?(this.C=!0,hGa(this),this.u?this.endScreen=new o3(a):this.endScreen=new s3(this.player)):this.env.Jc?this.endScreen=new q3(this.player):this.endScreen=new k3(this.player);g.C(this,this.endScreen);g.WN(this.player,this.endScreen.element,4);iGa(this);this.listeners.P(a,"videodatachange",this.Pa,this);this.listeners.P(a,g.tG("endscreen"),function(c){b.yd(c)});
this.listeners.P(a,g.uG("endscreen"),function(c){b.nf(c)})},hGa=function(a){var b=a.player.getVideoData();
if(!b||a.u===b.Ze&&a.B===b.kc)return!1;a.u=b.Ze;a.B=b.kc;return!0},gGa=function(a){a=a.S();
return a.ob&&!a.Jc},iGa=function(a){a.player.Qe("endscreen");
var b=a.player.getVideoData();b=new g.qG(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.qG(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});a.player.Jd([b,c])};
g.PN.prototype.gn=g.ca(4,function(){return this.app.gn()});
g.$V.prototype.gn=g.ca(3,function(){return this.getVideoData().AD});
g.u(f3,g.U);f3.prototype.select=function(){(this.J.Ji(this.suggestion.Ma().videoId,this.suggestion.Bd,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.Jx||void 0)||this.J.Y("web_player_endscreen_double_log_fix_killswitch"))&&this.J.vb(this.element)};
f3.prototype.onClick=function(a){g.AO(a,this.J,this.u,this.suggestion.Bd||void 0)&&this.select()};
f3.prototype.B=function(a){switch(a.keyCode){case 13:case 32:g.op(a)||(this.select(),g.np(a))}};
f3.prototype.Yd=function(a){g.K(this.element,"ytp-suggestion-card-with-margin",a)};g.u(h3,g.U);g.k=h3.prototype;g.k.Nr=function(a){this.suggestion!==a&&(this.suggestion=a,e3(this.u,a),this.playButton.za("url",this.suggestion.El()),this.Yd())};
g.k.Yd=function(){var a=this.J.ij(!0,this.J.isFullscreen());g.K(this.element,"ytp-autonav-endscreen-small-mode",this.Oe(a));g.K(this.element,"ytp-autonav-endscreen-is-premium",!!this.suggestion&&!!this.suggestion.Lv);g.K(this.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!this.J.wd());g.K(this.J.getRootNode(),"countdown-running",this.Ug());g.K(this.element,"ytp-player-content",this.J.wd());g.tg(this.overlay.element,{width:a.width+"px"});if(!this.Ug()){this.J.wd()?j3(this,Math.round(i3(this)/
1E3)):j3(this);a=!!this.suggestion&&!!this.suggestion.uq;var b=this.J.wd()||!a;g.K(this.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!b&&a);g.K(this.element,"ytp-autonav-endscreen-upnext-no-alternative-header",b&&!a);g.OL(this.B,this.J.wd())}};
g.k.Ug=function(){return 0<this.C};
g.k.Xp=function(){this.Ug()||(this.C=Date.now(),g3(this),cGa(this.J,i3(this)),g.K(this.J.getRootNode(),"countdown-running",this.Ug()))};
g.k.Kn=function(){this.Pk();g3(this)};
g.k.Pk=function(){this.Ug()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.Pk()};
g.k.KE=function(a){g.AO(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.vb(this.playButton.element):a.currentTarget===this.u.ha("ytp-autonav-endscreen-link-container")&&(a=this.u.ha("ytp-autonav-endscreen-link-container"),this.J.Qa(a,!0),this.J.vb(a)),this.select())};
g.k.CL=function(){this.J.vb(this.cancelButton.element);g.RN(this.J,!0)};
g.k.JE=function(){var a=this.J.wd();this.F&&this.bb!==a&&g.OL(this,a);this.Yd();this.J.Qa(this.element,a);this.J.Qa(this.cancelButton.element,a);this.J.Qa(this.u.ha("ytp-autonav-endscreen-link-container"),a);this.J.Qa(this.playButton.element,a)};
g.k.Oe=function(a){return 400>a.width||459>a.height};g.u(k3,g.U);g.k=k3.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.tq=function(){return!1};
g.k.wd=function(){return!1};
g.k.VD=function(){return!1};g.u(m3,g.U);g.k=m3.prototype;g.k.ut=function(){this.notification&&(this.D.stop(),this.Kb(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.Nr=function(a){this.suggestion=a;e3(this,a,"hqdefault.jpg")};
g.k.UE=function(){g.OL(this,this.api.wd());this.api.Qa(this.element,this.api.wd());this.api.Qa(this.ha("ytp-upnext-autoplay-icon"),this.api.wd());this.cancelButton&&this.api.Qa(this.cancelButton.element,this.api.wd())};
g.k.MO=function(){window.focus();this.ut()};
g.k.Xp=function(a){var b=this;this.Ug()||(g.Po("a11y-announce","Hierna "+this.suggestion.title),this.B=(0,g.M)(),this.u=new g.E(function(){n3(b,a)},25),n3(this,a),cGa(this.api,dGa(this,a)));
g.xn(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.U.prototype.hide.call(this)};
g.k.Ug=function(){return!!this.u};
g.k.Kn=function(){this.Pk();this.B=(0,g.M)();n3(this);g.J(this.element,"ytp-upnext-autoplay-paused")};
g.k.Pk=function(){this.Ug()&&(this.u.dispose(),this.u=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(g.P(this.api.S().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(b=this.suggestion.Ma(),this.ut(),this.notification=new Notification("Hierna",{body:b.title,icon:b.ue()}),this.C=this.P(this.notification,"click",this.MO),this.D.start())}this.Pk();this.api.nextVideo(!1,a)};
g.k.xM=function(a){!g.Pe(this.cancelButton.element,g.jp(a))&&g.AO(a,this.api)&&(this.api.wd()&&this.api.vb(this.ha("ytp-upnext-autoplay-icon")),this.select())};
g.k.wM=function(){this.api.wd()&&this.cancelButton&&this.api.vb(this.cancelButton.element);g.RN(this.api,!0)};
g.k.zO=function(a){l3(this);this.show();this.Xp(a)};
g.k.PH=function(a){l3(this);this.suggestion&&this.suggestion.Ma().videoId===a.Ma().videoId||this.Nr(a)};
g.k.AO=function(){l3(this);this.Pk();this.hide()};
g.k.ca=function(){this.Pk();this.ut();g.U.prototype.ca.call(this)};g.u(o3,k3);g.k=o3.prototype;g.k.create=function(){k3.prototype.create.call(this);this.D.P(this.player,"appresize",this.Yd);this.D.P(this.player,"onVideoAreaChange",this.Yd);this.D.P(this.player,"videodatachange",this.Pa);this.D.P(this.player,"autonavchange",this.IE);this.D.P(this.player,"autonavcancel",this.BL);this.Pa()};
g.k.show=function(){k3.prototype.show.call(this);(this.I||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.RN(this.player,!1);g.XN(this.player)&&this.tq()&&!this.C?(p3(this),2===this.videoData.autonavState?this.player.S().Y("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.u.select(!0):this.u.Xp():3===this.videoData.autonavState&&this.u.Kn()):(g.RN(this.player,!0),p3(this));this.Yd()};
g.k.hide=function(){k3.prototype.hide.call(this);this.u.Kn();p3(this)};
g.k.Yd=function(){var a=this.player.ij(!0,this.player.isFullscreen());p3(this);this.B.Yd();g.K(this.element,"ytp-autonav-cancelled-small-mode",this.Oe(a));g.K(this.element,"ytp-autonav-cancelled-tiny-mode",this.ou(a));g.K(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.tg(this.overlay.element,{width:a.width+"px"});if(!this.F){a=g.q(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){b=g.q(b.value);var c=b.next().value;b.next().value.Yd(1===c%2)}}};
g.k.Pa=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((this.suggestions=eGa(this,a))&&this.suggestions.length)for(this.u.Nr(this.suggestions[0]),this.u!==this.B&&this.B.Nr(this.suggestions[0]),a=0;a<jGa.length;++a){var b=jGa[a];if(this.suggestions&&this.suggestions[b]){this.videos[a]=new f3(this.player);var c=this.videos[a];b=this.suggestions[b];c.suggestion!==b&&(c.suggestion=b,e3(c,b));g.C(this,this.videos[a]);this.videos[a].fa(this.K.element)}}this.Yd()}};
g.k.IE=function(a){1===a?(this.I=!1,this.C=this.videoData.clientPlaybackNonce,this.u.Pk(),this.bb&&this.Yd()):(this.I=!0,this.wd()&&(2===a?this.u.Xp():3===a&&this.u.Kn()))};
g.k.BL=function(a){a?this.IE(1):(this.C=null,this.I=!1)};
g.k.tq=function(){return 1!==this.videoData.autonavState};
g.k.Oe=function(a){return(910>a.width||459>a.height)&&!this.ou(a)&&!(400>=a.width||360>=a.height)};
g.k.ou=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.wd=function(){return this.bb&&g.XN(this.player)&&this.tq()&&!this.C};
var jGa=[1,3,2,4];g.u(q3,k3);q3.prototype.na=function(){var a=this.player.getVideoData();this.u.update({profilePicture:a.hg,author:a.author});this.subscribeButton.channelId=a.Hg;var b=this.subscribeButton;a.subscribed?b.B():b.C()};g.u(r3,g.U);r3.prototype.select=function(){(this.api.Ji(this.suggestion.Ma().videoId,this.suggestion.Bd,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.Jx||void 0)||this.api.Y("web_player_endscreen_double_log_fix_killswitch"))&&this.api.vb(this.element)};
r3.prototype.onClick=function(a){g.AO(a,this.api,this.B,this.suggestion.Bd||void 0)&&this.select()};
r3.prototype.C=function(a){switch(a.keyCode){case 13:case 32:g.op(a)||(this.select(),g.np(a))}};
r3.prototype.Pa=function(){var a=this.api.getVideoData(),b=this.api.S();this.B=a.F?!1:b.B};g.u(s3,k3);g.k=s3.prototype;g.k.create=function(){k3.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=fGa(this,a),this.videoData=a);this.Yd();this.B.P(this.player,"appresize",this.Yd);this.B.P(this.player,"onVideoAreaChange",this.Yd);this.B.P(this.player,"videodatachange",this.Pa);this.B.P(this.player,"autonavchange",this.jz);this.B.P(this.player,"autonavcancel",this.DL);a=this.videoData.autonavState;a!==this.K&&this.jz(a);this.B.P(this.element,"transitionend",this.ZP)};
g.k.destroy=function(){g.Mt(this.B);g.cg(this.stills);this.stills=[];this.suggestions=null;k3.prototype.destroy.call(this);g.xn(this.element,"ytp-show-tiles");this.I.stop();this.K=this.videoData.autonavState};
g.k.tq=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){k3.prototype.show.call(this);g.xn(this.element,"ytp-show-tiles");this.player.S().u?g.qn(this.I):this.I.start();(this.F||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.RN(this.player,!1);t3(this)?(u3(this),2===this.videoData.autonavState?this.player.S().Y("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.u.select(!0):this.u.Xp():3===this.videoData.autonavState&&this.u.Kn()):(g.RN(this.player,!0),u3(this))};
g.k.hide=function(){k3.prototype.hide.call(this);this.u.Kn();u3(this)};
g.k.ZP=function(a){g.jp(a)===this.element&&this.Yd()};
g.k.Yd=function(){if(this.suggestions&&this.suggestions.length){g.J(this.element,"ytp-endscreen-paginate");var a=this.J.ij(!0,this.J.isFullscreen()),b=g.MN(this.J);b&&(b=b.xe()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,r=e/2,t=b<=f-2&&n>=r*m,w=e<=h-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&w)n-=p*m,e+=2;else if(t)n-=
r*m,b+=2;else if(w)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Jg(a,m,n);g.tg(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.u.Nr(this.suggestions[0]);this.u instanceof h3&&this.u.Yd();g.K(this.element,"ytp-endscreen-takeover",t3(this));u3(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,r=0,d&&f>=b-2&&h>=e-2?
r=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(r=2):r=2),p=g.fe(p+this.C,l),0!==r){t=this.stills[c];t||(t=new r3(this.player),this.stills[c]=t,a.appendChild(t.element));w=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+r)/e)-w-4,F=Math.floor(m*(f+r)/b)-x-4;g.Cg(t.element,x,w);g.Jg(t.element,F,y);g.tg(t.element,"transitionDelay",(h+f)/20+"s");g.K(t.element,"ytp-videowall-still-mini",1===r);g.K(t.element,"ytp-videowall-still-large",2<r);r=t;p=this.suggestions[p];r.suggestion!==p&&(r.suggestion=
p,t=r.api.S(),w=g.vn(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",e3(r,p,w),g.mD(t)&&(t=p.El(),t=g.Nd(t,g.eP("emb_rel_end")),r.za("url",t)),(p=(p=p.Bd)&&p.itct)&&r.api.nm(r.element,p));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.Me(e.element),g.bg(e);this.stills.length=c}};
g.k.Pa=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.C=0,this.suggestions=fGa(this,a),this.videoData=a,this.Yd())};
g.k.EL=function(){this.C+=this.stills.length;this.Yd()};
g.k.FL=function(){this.C-=this.stills.length;this.Yd()};
g.k.VD=function(){return this.u.Ug()};
g.k.jz=function(a){1===a?(this.F=!1,this.D=this.videoData.clientPlaybackNonce,this.u.Pk(),this.bb&&this.Yd()):(this.F=!0,this.bb&&t3(this)&&(2===a?this.u.Xp():3===a&&this.u.Kn()))};
g.k.DL=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.Qa(this.stills[a].element,!0);this.jz(1)}else this.D=null,this.F=!1;this.Yd()};
g.k.wd=function(){return this.bb&&t3(this)};g.u(v3,g.hO);g.k=v3.prototype;g.k.Sn=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!gGa(this.player)||b;var c=a.Tc||g.vD(a.D),d=this.player.Uq();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.wd=function(){return this.endScreen.wd()};
g.k.DK=function(){return this.wd()?this.endScreen.VD():!1};
g.k.ca=function(){this.player.Qe("endscreen");g.hO.prototype.ca.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.BD;if(b&&b.videoId){var c=this.player.Sa().Wc.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].id&&!a.tB?a=!1:(this.player.Ji(b.videoId,void 0,void 0,!0,!0,b),c&&c.wu("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.hO.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.hO.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.yd=function(a){this.Sn()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.nf=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.Pa=function(){iGa(this);this.C&&hGa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.u?this.endScreen=new o3(this.player):this.endScreen=new s3(this.player),g.C(this,this.endScreen),g.WN(this.player,this.endScreen.element,4))};g.nO.endscreen=v3;})(_yt_player);
